
SELECT * FROM GP_Details WHERE County = ' '
SELECT Address1, Address2, Address3, City, County FROM GP_Details WHERE City = 'London' OR County = 'London'
SELECT Address1, Address2, Address3, City, County FROM GP_Details WHERE City = 'Bedfordshire' OR County = 'Bedfordshire'
SELECT Address1, Address2, Address3, City, County FROM GP_Details WHERE City = 'Berkshire' OR County = 'Berkshire'
SELECT Address1, Address2, Address3, City, County FROM GP_Details WHERE City = 'Bristol' OR County = 'Bristol'
SELECT Address1, Address2, Address3, City, County FROM GP_Details WHERE City = 'Buckinghamshire' OR County = 'Buckinghamshire'
SELECT Address1, Address2, Address3, City, County FROM GP_Details WHERE City = 'Cambridgeshire' OR County = 'Cambridgeshire'
SELECT Address1, Address2, Address3, City, County FROM GP_Details WHERE City = 'Cheshire' OR County = 'Cheshire'
SELECT Address1, Address2, Address3, City, County FROM GP_Details WHERE City = 'Cornwall' OR County = 'Cornwall'
SELECT Address1, Address2, Address3, City, County FROM GP_Details WHERE City = 'Cumbria' OR County = 'Cumbria'
SELECT Address1, Address2, Address3, City, County FROM GP_Details WHERE City = 'Derbyshire' OR County = 'Derbyshire'
SELECT Address1, Address2, Address3, City, County FROM GP_Details WHERE City = 'Devon' OR County = 'Devon'
SELECT Address1, Address2, Address3, City, County FROM GP_Details WHERE City = 'Dorset' OR County = 'Dorset'
SELECT Address1, Address2, Address3, City, County FROM GP_Details WHERE City = 'Durham' OR County = 'Durham'
SELECT Address1, Address2, Address3, City, County FROM GP_Details WHERE City = 'East Riding of Yorkshire' OR County = 'East Riding of Yorkshire'
SELECT Address1, Address2, Address3, City, County FROM GP_Details WHERE City = 'East Sussex' OR County = 'East Sussex'
SELECT Address1, Address2, Address3, City, County FROM GP_Details WHERE City = 'Essex' OR County = 'Essex'
SELECT Address1, Address2, Address3, City, County FROM GP_Details WHERE City = 'Gloucestershire' OR County = 'Gloucestershire'
SELECT Address1, Address2, Address3, City, County FROM GP_Details WHERE City = 'Greater Manchester' OR County = 'Greater Manchester'

