//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHSPatServ
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_Disease_Prevalence
    {
        public int GP_Disease_PrevalenceID { get; set; }
        public Nullable<int> Ref_ { get; set; }
        public string Indicator_Group { get; set; }
        public string Disease_Name { get; set; }
        public int Number_of_cases { get; set; }
    
        public virtual GP_Practice_Code GP_Practice_Code { get; set; }
    }
}
