//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHSPatServ
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_Practice_Code
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GP_Practice_Code()
        {
            this.GP_Disease_Prevalence = new HashSet<GP_Disease_Prevalence>();
            this.GP_Ratings = new HashSet<GP_Ratings>();
            this.GP_Total_Numbers = new HashSet<GP_Total_Numbers>();
        }
    
        public int GP_Practice_CodeID { get; set; }
        public string OrganisationCode { get; set; }
        public int Ref_Organisation_Details_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GP_Disease_Prevalence> GP_Disease_Prevalence { get; set; }
        public virtual Organisation_Details Organisation_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GP_Ratings> GP_Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GP_Total_Numbers> GP_Total_Numbers { get; set; }
    }
}
