//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHSPatServ
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_Ratings
    {
        public int GP_RatingsID { get; set; }
        public Nullable<int> Ref_ { get; set; }
        public Nullable<double> Q14_On_Same_day { get; set; }
        public Nullable<double> Q14_Next_Working_Day { get; set; }
        public Nullable<double> Q14_Few_Days_Later { get; set; }
        public Nullable<double> Q14_Week_Or_More { get; set; }
        public Nullable<double> Q14_Cant_Remember { get; set; }
        public Nullable<double> Q28_Very_Good { get; set; }
        public Nullable<double> Q28_Fairly_Good { get; set; }
        public Nullable<double> Q28_Neither { get; set; }
        public Nullable<double> Q28_Fairly_Poor { get; set; }
        public Nullable<double> Q28_Very_Poor { get; set; }
        public Nullable<double> Q29_Definitely_Yes { get; set; }
        public Nullable<double> Q29_Probably_Yes { get; set; }
        public Nullable<double> Q29_Not_Sure { get; set; }
        public Nullable<double> Q29_Probably_Not { get; set; }
        public Nullable<double> Q29_Definitely_Not { get; set; }
        public Nullable<double> Q29_Dont_Know { get; set; }
    
        public virtual GP_Practice_Code GP_Practice_Code { get; set; }
    }
}
