//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHSPatServ
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_Total_Numbers
    {
        public int GP_Total_NumbersID { get; set; }
        public Nullable<int> Ref_ { get; set; }
        public int Total_Male { get; set; }
        public int Total_Female { get; set; }
    
        public virtual GP_Practice_Code GP_Practice_Code { get; set; }
    }
}
