//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHS_Patient_Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_Services
    {
        public int Service_ID { get; set; }
        public string GP_Service_Name { get; set; }
    }
}
